version: "3.9"
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "@administration2025"
    volumes:
      - sqlserverdata:/var/opt/mssql

volumes:
  sqlserverdata:
    
networks:
  bridge_network:
    driver: bridge
