apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: podyam
    enviroment: paolaflores
  name: podyam
spec:
  containers:
  - image: nginx
    volumeMounts:
    mountPath: "/scratch"
    name: podyam
    resources: {}
  volumes:
    name: my-volume
    emptyDir:
    sizeLimit: 50Mi
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
