name: Greeting on variable day

on:
  workflow_dispatch

env:
  DAY_OF_WEEK: Monday

jobs:
  greeting__job:
    runs-on: ubuntu-latest
    env:
      Greeting: Hello
    steps:
      - name: "Say hello Liss is Monday" 
        run: echo "$Greeting $First_Name, Today is $DAY_OF_WEEK!" 
        env: 
          First_Name: Liss  
